async function loadAndShowRandomQuote() {//function for quotes
    try {
        const res = await fetch('quotes.txt');//quotes text file (just replace quotes.txt with your own file)
        if (!res.ok) throw new Error('Failed to load quotes.txt: ' + res.status);
        const text = await res.text();// reads the text from the response
        const quotes = text.split(/\r?\n/)// splits the text into lines
            .map(s => s.trim())
            .filter(Boolean);//filters only boolean values(no empty lines)
        if (quotes.length === 0) {//no quotes errors
            console.warn('No quotes found in quotes.txt');//no quotes error log
            return;
        }ote = quotes[Math.floor(Math.random() * quotes.length)];//randomly selects quote
        consol
        const que.log(quote);//logs random quote
    } catch (err) {//errors
        console.error('Error loading quotes:', err);//logs errors
    }
}
loadAndShowRandomQuote();//calls the function to load and show a random quote



//feel free to modify and use it in your own projects
//quotes in quotes.txt file should be separated by enters

//quotes.txt are orginaly generated by AI, so you might want to replace them
